<?php

namespace ut8ia\contentmodule;

use \yii\base\Module;

class ContentModule extends Module
{

    public $sectionId;
    public $multilanguage;
    public $positioning;
    public $stick;
    public $navigationTags;
    public $display_format;
    public $display_formats;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


}


?>
