<?php

namespace ut8ia\contentmodule;

use \yii\base\Module;

class ContentModule extends Module {

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


}



?>